# Generated by Django 6.0.2 on 2026-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='causes/covers/'),
        ),
    ]
