# Generated by Django 6.0.2 on 2026-04-11 12:00

from django.db import migrations
from django.utils.text import slugify


def migrate_category_data(apps, schema_editor):
    """
    Migrate existing category strings to Category model instances
    and populate the category_fk field.
    """
    Cause = apps.get_model('causes', 'Cause')
    Category = apps.get_model('causes', 'Category')
    
    # Get all unique category values from existing causes
    unique_categories = Cause.objects.values_list('category', flat=True).distinct()
    
    # Create Category objects for each unique value
    category_map = {}
    for cat_name in unique_categories:
        if cat_name:  # Skip empty strings
            category, created = Category.objects.get_or_create(
                name=cat_name,
                defaults={'slug': slugify(cat_name)}
            )
            category_map[cat_name] = category
    
    # Update all causes with the new category_fk
    for cause in Cause.objects.all():
        if cause.category in category_map:
            cause.category_fk = category_map[cause.category]
            cause.save()


def reverse_migrate_category_data(apps, schema_editor):
    """
    Reverse migration: clear category_fk values.
    """
    Cause = apps.get_model('causes', 'Cause')
    Cause.objects.all().update(category_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_category'),
    ]

    operations = [
        migrations.RunPython(migrate_category_data, reverse_migrate_category_data),
    ]
