# Generated by Django 6.0.2 on 2026-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('kra_pin', models.CharField(max_length=20, unique=True)),
                ('tcc_number', models.CharField(max_length=50, unique=True)),
                ('tcc_document', models.FileField(upload_to='organization_documents/tccs/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('payout_method', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till'), ('BANK', 'Bank Transfer')], default='BANK', max_length=20)),
                ('payout_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_shortcode', models.CharField(blank=True, max_length=20, null=True)),
                ('payout_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('physical_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
