# Generated by Django 6.0.2 on 2026-04-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0005_migrate_category_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='category',
        ),
        migrations.RenameField(
            model_name='cause',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='cause',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causes', to='causes.category'),
        ),
    ]
