# Generated by Django 6.0.2 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="expense_category",
            field=models.CharField(default="Uncategorized", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="funds_utilized",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
