# Generated by Django 6.0.2 on 2026-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_frontend_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='expense_category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
